### ISSUE TITLE
How to show the head_pose results?

### ISSUE THREAD

**Issue by lz199144** [OSUrobotics/ros-head-tracking#3]
Hi gays!
I use openni_launch and head_tracking to get head pose, I find the head_pose topic has published, and the format is geometry_msgs/PoseStamped.
Which ros package can show this format result?

**Comment by dlaz** [comment]
What exactly do you want to do? For visualization, there's [rviz](http://wiki.ros.org/rviz). If you just want to see the raw data, you can use [rostopic echo](http://wiki.ros.org/rostopic#rostopic_echo).
